var annotated_dup =
[
    [ "Arch", "d9/dc3/namespace_arch.html", "d9/dc3/namespace_arch" ],
    [ "Boot", "da/d80/namespace_boot.html", "da/d80/namespace_boot" ],
    [ "GDT", "dc/d49/namespace_g_d_t.html", "dc/d49/namespace_g_d_t" ],
    [ "Graphics", "d6/d9b/namespace_graphics.html", "d6/d9b/namespace_graphics" ],
    [ "IDT", "db/d3c/namespace_i_d_t.html", "db/d3c/namespace_i_d_t" ],
    [ "LinkedList", "d0/d34/namespace_linked_list.html", "d0/d34/namespace_linked_list" ],
    [ "Memory", "db/d2f/namespace_memory.html", "db/d2f/namespace_memory" ],
    [ "Time", "d6/da1/namespace_time.html", "d6/da1/namespace_time" ],
    [ "Bitset", "d6/d09/class_bitset.html", "d6/d09/class_bitset" ],
    [ "CR0", "dd/dc6/struct_c_r0.html", "dd/dc6/struct_c_r0" ],
    [ "CR2", "dc/df1/struct_c_r2.html", "dc/df1/struct_c_r2" ],
    [ "CR3", "d9/d5d/struct_c_r3.html", "d9/d5d/struct_c_r3" ],
    [ "Directory", "d5/d2b/struct_directory.html", "d5/d2b/struct_directory" ],
    [ "DirectoryEntry", "db/dc4/struct_directory_entry.html", "db/dc4/struct_directory_entry" ],
    [ "Frame", "d5/d15/struct_frame.html", "d5/d15/struct_frame" ],
    [ "GDTR", "da/d33/struct_g_d_t_r.html", "da/d33/struct_g_d_t_r" ],
    [ "IDTR", "dc/d6a/struct_i_d_t_r.html", "dc/d6a/struct_i_d_t_r" ],
    [ "Mutex", "d4/de8/class_mutex.html", "d4/de8/class_mutex" ],
    [ "Page", "df/d9b/struct_page.html", "df/d9b/struct_page" ],
    [ "registers", "df/d94/structregisters.html", "df/d94/structregisters" ],
    [ "RingBuffer", "d4/d8f/class_ring_buffer.html", "d4/d8f/class_ring_buffer" ],
    [ "Semaphore", "d4/dbd/class_semaphore.html", "d4/dbd/class_semaphore" ],
    [ "Table", "d5/d0d/struct_table.html", "d5/d0d/struct_table" ],
    [ "TableEntry", "d5/d8c/struct_table_entry.html", "d5/d8c/struct_table_entry" ],
    [ "task", "db/da2/structtask.html", "db/da2/structtask" ],
    [ "task_sync", "dd/dc4/structtask__sync.html", "dd/dc4/structtask__sync" ],
    [ "tasklist", "df/d8a/structtasklist.html", "df/d8a/structtasklist" ],
    [ "tss_entry", "d5/d29/structtss__entry.html", "d5/d29/structtss__entry" ]
];