var annotated_dup =
[
    [ "Boot", "da/d80/namespace_boot.html", "da/d80/namespace_boot" ],
    [ "Graphics", "d6/d9b/namespace_graphics.html", "d6/d9b/namespace_graphics" ],
    [ "LinkedList", "d0/d34/namespace_linked_list.html", "d0/d34/namespace_linked_list" ],
    [ "Registers", "d4/ddf/namespace_registers.html", "d4/ddf/namespace_registers" ],
    [ "Time", "d6/da1/namespace_time.html", "d6/da1/namespace_time" ],
    [ "address", "d7/d61/unionaddress.html", "d7/d61/unionaddress" ],
    [ "Bitset", "d6/d09/class_bitset.html", "d6/d09/class_bitset" ],
    [ "frame", "d5/d77/structframe.html", "d5/d77/structframe" ],
    [ "gdt_entry", "d8/dc9/structgdt__entry.html", "d8/dc9/structgdt__entry" ],
    [ "gdt_ptr", "d7/d4a/structgdt__ptr.html", "d7/d4a/structgdt__ptr" ],
    [ "idt_gate", "d4/d96/structidt__gate.html", "d4/d96/structidt__gate" ],
    [ "idt_register", "d3/d1c/structidt__register.html", "d3/d1c/structidt__register" ],
    [ "Mutex", "d4/de8/class_mutex.html", "d4/de8/class_mutex" ],
    [ "page", "d7/d1a/structpage.html", "d7/d1a/structpage" ],
    [ "page_directory", "d7/dc8/structpage__directory.html", "d7/dc8/structpage__directory" ],
    [ "page_directory_entry", "dd/df9/structpage__directory__entry.html", "dd/df9/structpage__directory__entry" ],
    [ "page_table", "d4/dc1/structpage__table.html", "d4/dc1/structpage__table" ],
    [ "page_table_entry", "d0/d0c/structpage__table__entry.html", "d0/d0c/structpage__table__entry" ],
    [ "registers", "df/d94/structregisters.html", "df/d94/structregisters" ],
    [ "RingBuffer", "d4/d8f/class_ring_buffer.html", "d4/d8f/class_ring_buffer" ],
    [ "Semaphore", "d4/dbd/class_semaphore.html", "d4/dbd/class_semaphore" ],
    [ "stackframe", "db/dcb/structstackframe.html", "db/dcb/structstackframe" ],
    [ "task", "db/da2/structtask.html", "db/da2/structtask" ],
    [ "task_sync", "dd/dc4/structtask__sync.html", "dd/dc4/structtask__sync" ],
    [ "tasklist", "df/d8a/structtasklist.html", "df/d8a/structtasklist" ],
    [ "tss_entry", "d5/d29/structtss__entry.html", "d5/d29/structtss__entry" ]
];