var files_dup =
[
    [ "animation.cpp", "d8/ddb/animation_8cpp.html", "d8/ddb/animation_8cpp" ],
    [ "animation.hpp", "d6/d5a/animation_8hpp.html", "d6/d5a/animation_8hpp" ],
    [ "Arch.hpp", "d7/d9c/_arch_8hpp.html", "d7/d9c/_arch_8hpp" ],
    [ "Arch.i686.cpp", "d4/dc9/_arch_8i686_8cpp.html", "d4/dc9/_arch_8i686_8cpp" ],
    [ "Arch.i686.hpp", "d7/dcf/_arch_8i686_8hpp.html", [
      [ "stackframe", "d5/d3e/struct_arch_1_1stackframe.html", "d5/d3e/struct_arch_1_1stackframe" ]
    ] ],
    [ "Arguments.cpp", "d4/d85/_arguments_8cpp.html", "d4/d85/_arguments_8cpp" ],
    [ "Arguments.hpp", "d5/d87/_arguments_8hpp.html", "d5/d87/_arguments_8hpp" ],
    [ "assert.hpp", "d2/d54/assert_8hpp.html", "d2/d54/assert_8hpp" ],
    [ "Bitset.hpp", "d9/d35/_bitset_8hpp.html", [
      [ "Bitset", "d6/d09/class_bitset.html", "d6/d09/class_bitset" ]
    ] ],
    [ "console.cpp", "d9/dda/console_8cpp.html", "d9/dda/console_8cpp" ],
    [ "console.hpp", "d5/ddc/console_8hpp.html", "d5/ddc/console_8hpp" ],
    [ "crti.h", "d5/d64/crti_8h.html", "d5/d64/crti_8h" ],
    [ "crti.s", "d1/d76/crti_8s.html", null ],
    [ "crtn.s", "d4/da6/crtn_8s.html", null ],
    [ "cxx.cpp", "d1/dd1/cxx_8cpp.html", "d1/dd1/cxx_8cpp" ],
    [ "defines.hpp", "db/df8/defines_8hpp.html", "db/df8/defines_8hpp" ],
    [ "EarlyPanic.cpp", "dd/dad/_early_panic_8cpp.html", "dd/dad/_early_panic_8cpp" ],
    [ "EarlyPanic.hpp", "d2/d76/_early_panic_8hpp.html", "d2/d76/_early_panic_8hpp" ],
    [ "Entry.cpp", "d4/d01/_entry_8cpp.html", "d4/d01/_entry_8cpp" ],
    [ "errno.cpp", "d1/db0/errno_8cpp.html", "d1/db0/errno_8cpp" ],
    [ "errno.hpp", "d7/dae/errno_8hpp.html", "d7/dae/errno_8hpp" ],
    [ "Flush.h", "db/dc9/_flush_8h.html", "db/dc9/_flush_8h" ],
    [ "flush.s", "d7/d00/flush_8s.html", null ],
    [ "font.cpp", "dd/d53/font_8cpp.html", "dd/d53/font_8cpp" ],
    [ "font.hpp", "df/d50/font_8hpp.html", "df/d50/font_8hpp" ],
    [ "framebuffer.cpp", "d3/dd6/framebuffer_8cpp.html", "d3/dd6/framebuffer_8cpp" ],
    [ "framebuffer.hpp", "d7/d1a/framebuffer_8hpp.html", "d7/d1a/framebuffer_8hpp" ],
    [ "gcc.cpp", "d4/db1/gcc_8cpp.html", "d4/db1/gcc_8cpp" ],
    [ "gdt.cpp", "d7/de6/gdt_8cpp.html", "d7/de6/gdt_8cpp" ],
    [ "gdt.hpp", "df/d77/gdt_8hpp.html", "df/d77/gdt_8hpp" ],
    [ "graphics.cpp", "d6/d99/graphics_8cpp.html", "d6/d99/graphics_8cpp" ],
    [ "graphics.hpp", "d9/d31/graphics_8hpp.html", "d9/d31/graphics_8hpp" ],
    [ "Handoff.cpp", "d4/d88/_handoff_8cpp.html", "d4/d88/_handoff_8cpp" ],
    [ "Handoff.hpp", "d2/d1f/_handoff_8hpp.html", "d2/d1f/_handoff_8hpp" ],
    [ "heap.cpp", "de/d90/heap_8cpp.html", "de/d90/heap_8cpp" ],
    [ "heap.hpp", "da/d45/heap_8hpp.html", "da/d45/heap_8hpp" ],
    [ "idt.cpp", "d9/d87/idt_8cpp.html", "d9/d87/idt_8cpp" ],
    [ "idt.hpp", "dd/d12/idt_8hpp.html", "dd/d12/idt_8hpp" ],
    [ "interrupt.s", "d6/dcb/interrupt_8s.html", null ],
    [ "Interrupts.h", "d7/d03/_interrupts_8h.html", "d7/d03/_interrupts_8h" ],
    [ "isr.cpp", "d3/d68/isr_8cpp.html", "d3/d68/isr_8cpp" ],
    [ "isr.hpp", "d4/ddc/isr_8hpp.html", "d4/ddc/isr_8hpp" ],
    [ "LinkedList.hpp", "d5/d72/_linked_list_8hpp.html", [
      [ "LinkedListNode", "d1/ddb/class_linked_list_1_1_linked_list_node.html", "d1/ddb/class_linked_list_1_1_linked_list_node" ],
      [ "LinkedList", "d9/d3d/class_linked_list_1_1_linked_list.html", "d9/d3d/class_linked_list_1_1_linked_list" ]
    ] ],
    [ "Loader.cpp", "d1/d51/_loader_8cpp.html", "d1/d51/_loader_8cpp" ],
    [ "Loader.hpp", "dc/dc7/_loader_8hpp.html", "dc/dc7/_loader_8hpp" ],
    [ "Logger.cpp", "de/d27/_logger_8cpp.html", "de/d27/_logger_8cpp" ],
    [ "Logger.hpp", "d3/de3/_logger_8hpp.html", [
      [ "Logger", "d3/d42/class_logger.html", "d3/d42/class_logger" ]
    ] ],
    [ "Memory.hpp", "d9/d4f/_memory_8hpp.html", "d9/d4f/_memory_8hpp" ],
    [ "Memory.i686.hpp", "d7/d42/_memory_8i686_8hpp.html", "d7/d42/_memory_8i686_8hpp" ],
    [ "MemoryMap.hpp", "d6/dc1/_memory_map_8hpp.html", [
      [ "MemoryMap", "d0/dea/class_memory_1_1_memory_map.html", "d0/dea/class_memory_1_1_memory_map" ]
    ] ],
    [ "MemorySection.hpp", "d0/d91/_memory_section_8hpp.html", "d0/d91/_memory_section_8hpp" ],
    [ "Mutex.cpp", "da/d4c/_mutex_8cpp.html", null ],
    [ "Mutex.hpp", "d4/d48/_mutex_8hpp.html", [
      [ "Mutex", "d4/de8/class_mutex.html", "d4/de8/class_mutex" ]
    ] ],
    [ "NullBoot.c", "d0/d0c/_null_boot_8c.html", "d0/d0c/_null_boot_8c" ],
    [ "paging.cpp", "d1/d5e/paging_8cpp.html", "d1/d5e/paging_8cpp" ],
    [ "paging.hpp", "d1/d75/paging_8hpp.html", "d1/d75/paging_8hpp" ],
    [ "Panic.cpp", "d9/d5d/_panic_8cpp.html", "d9/d5d/_panic_8cpp" ],
    [ "Panic.hpp", "d6/d64/_panic_8hpp.html", "d6/d64/_panic_8hpp" ],
    [ "Physical.hpp", "d0/d81/_physical_8hpp.html", "d0/d81/_physical_8hpp" ],
    [ "ports.cpp", "d7/d27/ports_8cpp.html", "d7/d27/ports_8cpp" ],
    [ "ports.hpp", "d8/d9f/ports_8hpp.html", "d8/d9f/ports_8hpp" ],
    [ "primes.cpp", "d0/dde/primes_8cpp.html", "d0/dde/primes_8cpp" ],
    [ "primes.hpp", "d3/dee/primes_8hpp.html", "d3/dee/primes_8hpp" ],
    [ "printf.cpp", "d4/d64/printf_8cpp.html", "d4/d64/printf_8cpp" ],
    [ "RAII.hpp", "db/d52/_r_a_i_i_8hpp.html", "db/d52/_r_a_i_i_8hpp" ],
    [ "rand.cpp", "d5/d92/rand_8cpp.html", "d5/d92/rand_8cpp" ],
    [ "rand.hpp", "d4/d0b/rand_8hpp.html", "d4/d0b/rand_8hpp" ],
    [ "regs.hpp", "d8/dfb/regs_8hpp.html", "d8/dfb/regs_8hpp" ],
    [ "RingBuffer.hpp", "d6/d15/_ring_buffer_8hpp.html", [
      [ "RingBuffer", "d4/d8f/class_ring_buffer.html", "d4/d8f/class_ring_buffer" ]
    ] ],
    [ "rs232.cpp", "d4/dc7/rs232_8cpp.html", "d4/dc7/rs232_8cpp" ],
    [ "rs232.hpp", "db/d90/rs232_8hpp.html", "db/d90/rs232_8hpp" ],
    [ "rtc.cpp", "dd/d82/rtc_8cpp.html", "dd/d82/rtc_8cpp" ],
    [ "rtc.hpp", "d9/d89/rtc_8hpp.html", "d9/d89/rtc_8hpp" ],
    [ "sections.hpp", "d0/d29/sections_8hpp.html", "d0/d29/sections_8hpp" ],
    [ "Semaphore.cpp", "d6/d80/_semaphore_8cpp.html", "d6/d80/_semaphore_8cpp" ],
    [ "Semaphore.hpp", "d4/dae/_semaphore_8hpp.html", [
      [ "Semaphore", "d4/dbd/class_semaphore.html", "d4/dbd/class_semaphore" ]
    ] ],
    [ "spinner.cpp", "df/d57/spinner_8cpp.html", "df/d57/spinner_8cpp" ],
    [ "spinner.hpp", "da/d14/spinner_8hpp.html", "da/d14/spinner_8hpp" ],
    [ "spkr.cpp", "da/da5/spkr_8cpp.html", "da/da5/spkr_8cpp" ],
    [ "spkr.hpp", "da/d1a/spkr_8hpp.html", "da/d1a/spkr_8hpp" ],
    [ "Stacktrace.cpp", "d3/ddc/_stacktrace_8cpp.html", "d3/ddc/_stacktrace_8cpp" ],
    [ "Stacktrace.hpp", "de/df5/_stacktrace_8hpp.html", "de/df5/_stacktrace_8hpp" ],
    [ "stdio.hpp", "d2/daf/stdio_8hpp.html", "d2/daf/stdio_8hpp" ],
    [ "stivale2.c", "dc/d20/stivale2_8c.html", "dc/d20/stivale2_8c" ],
    [ "string.cpp", "d5/d24/string_8cpp.html", "d5/d24/string_8cpp" ],
    [ "string.hpp", "d4/da0/string_8hpp.html", "d4/da0/string_8hpp" ],
    [ "tasks.cpp", "d5/d9d/tasks_8cpp.html", "d5/d9d/tasks_8cpp" ],
    [ "tasks.hpp", "d2/dbd/tasks_8hpp.html", "d2/dbd/tasks_8hpp" ],
    [ "tasks.s", "d0/d29/tasks_8s.html", null ],
    [ "time.cpp", "de/daf/time_8cpp.html", null ],
    [ "time.hpp", "de/d99/time_8hpp.html", [
      [ "TimeDescriptor", "d9/dfc/class_time_1_1_time_descriptor.html", "d9/dfc/class_time_1_1_time_descriptor" ]
    ] ],
    [ "timer.cpp", "dc/de5/timer_8cpp.html", "dc/de5/timer_8cpp" ],
    [ "timer.hpp", "df/d05/timer_8hpp.html", "df/d05/timer_8hpp" ],
    [ "tss.hpp", "d2/d59/tss_8hpp.html", "d2/d59/tss_8hpp" ]
];