name: Build on External Push

on:
  workflow_dispatch:
  repository_dispatch:
    types: [push_dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update packages
        run: sudo apt update
      - name: Install packages
        run: sudo apt install rsync doxygen-latex graphviz scons
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
          repository: XyrisOS/xyris
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Build Xyris Docs
        run: python $(which scons) docs
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: Documentation/Build/html
